theme: jekyll-theme-cayman
title: ExpressionsEditor & \nComboGestureExpressions (EE/CGE)
description: Easily create face expressions animations, and generate Avatars 3.0 animator layers for hand gestures to control face expressions 
