theme: jekyll-theme-cayman
title: ComboGestureExpressions V2
description: Attach face expressions to hand gestures, and make it react to Avatars 3.0's features, including Contacts, PhysBones and OSC. 
